#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - bash-completion
runcmd:
  - |
    echo "Installing k3s..."
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -
  - |
    echo "Enable kubectl completion for root"
    echo 'source <(kubectl completion bash)' >> /root/.bashrc
    echo 'alias k=kubectl' >> /root/.bashrc
    echo 'complete -o default -F __start_kubectl k' >> /root/.bashrc
  - |
    echo "Initializing ArgoCD..."
    kubectl create namespace argocd || true
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    kubectl rollout status deployment/argocd-server -n argocd --timeout=180s
    git clone https://github.com/Kajetan7/homelab-infra.git /root/homelab-infra
    kubectl apply -n argocd -f /root/homelab-infra/k3s-lab-vm/bootstrap/argocd
  - |
    echo "Done. You can now SSH and run: sudo su - ; kubectl get nodes"
