name: CV Page - Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "apply or destroy"
        required: true
        default: "apply"
        type: choice
        options: [apply, destroy]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      TF_VAR_docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    defaults:
      run:
        working-directory: cv-page
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: inputs.action == 'apply'
        run: terraform plan

      - name: Terraform Apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: Terraform Plan Destroy
        if: inputs.action == 'destroy'
        run: terraform plan -destroy

      - name: Terraform Destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -auto-approve
